# Generated by Django 5.1.5 on 2025-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('session_id', models.CharField(max_length=255)),
                ('csrftoken', models.CharField(max_length=255)),
                ('x_ig_app_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
