# Generated by Django 5.1.5 on 2025-02-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='instagramuser',
            name='username',
        ),
    ]
