# Generated by Django 5.1.5 on 2025-02-03 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_instagramuser_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramUser',
            new_name='InstagramUser_data',
        ),
    ]
