# Generated by Django 5.1.5 on 2025-02-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_instagramuser_instagramuser_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser_data',
            name='new_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='old_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
