# Generated by Django 5.1.5 on 2025-02-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_instagramuser_data_new_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser_data',
            name='user1_id',
            field=models.CharField(max_length=100),
        ),
    ]
