# Generated by Django 5.1.5 on 2025-02-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_instagramuser_data_user1_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramuser_data',
            old_name='new_list',
            new_name='new_followers_list',
        ),
        migrations.RenameField(
            model_name='instagramuser_data',
            old_name='old_list',
            new_name='new_following_list',
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='old_followers_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='old_following_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='who_remove_follow',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
