# Generated by Django 5.1.5 on 2025-02-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_new_followers_list_instagramuser_data_followers_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser_data',
            name='who_i_dont_he_follow',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='who_i_follow_he_dont',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
