# Generated by Django 5.1.5 on 2025-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_who_i_dont_he_follow_instagramuser_data_who_i_dont_follow_he_followback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser_data',
            name='instagram_biography',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='instagram_follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='instagram_following_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='instagram_full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='instagram_profile_picture_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='instagram_total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
