# Generated by Django 5.1.5 on 2025-02-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_instagramuser_data_instagram_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser_data',
            name='instagram_profile_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='instagramuser_data',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
