# Generated by Django 5.1.5 on 2025-02-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_instagramuser_data_instagram_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser_data',
            name='instagram_profile_picture_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
