# Generated by Django 5.1.5 on 2025-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_instagramuser_data_instagram_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser_data',
            name='unfollowed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
