# Generated by Django 5.1.5 on 2025-03-05 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_front_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramuser_data',
            name='last_time_fetched',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
