# Generated by Django 5.1.5 on 2025-03-06 01:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_instagramuser_data_last_time_fetched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='front_flags',
            new_name='FrontFlags',
        ),
    ]
