# Generated by Django 5.1.5 on 2025-03-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_frontflags_is_first_time_connected_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser_data',
            name='instagram_follower_count',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramuser_data',
            name='instagram_following_count',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='instagramuser_data',
            name='instagram_total_posts',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
