# Generated by Django 5.1.5 on 2025-03-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_followers_list_instagramuser_data_new_followers_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramuser_data',
            old_name='who_remove_follow',
            new_name='who_remove_following',
        ),
        migrations.AddField(
            model_name='instagramuser_data',
            name='whos_removed_follower',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
