# Generated by Django 5.1.5 on 2025-03-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_who_remove_follow_instagramuser_data_who_remove_following_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramuser_data',
            old_name='who_remove_following',
            new_name='who_removed_follower',
        ),
        migrations.RenameField(
            model_name='instagramuser_data',
            old_name='whos_removed_follower',
            new_name='who_removed_following',
        ),
    ]
