# Generated by Django 5.1.5 on 2025-04-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='credit_amount',
            field=models.PositiveIntegerField(choices=[(50, '50 Credits'), (10, '10 Credits')], null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.CharField(max_length=50),
        ),
    ]
