# Generated by Django 5.1.5 on 2025-04-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_subscription_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
    ]
