# Generated by Django 5.1.5 on 2025-04-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='credits_removed',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='credits_added',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
