# Generated by Django 5.1.5 on 2025-04-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymenthistory_credits_removed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='credits_removed',
        ),
    ]
