# Generated by Django 5.1.5 on 2025-04-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_subscriptionhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
    ]
