# Generated by Django 5.1.5 on 2025-04-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_delete_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='credits_reduced',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
