# Generated by Django 5.1.5 on 2025-04-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_subscription_credits_reduced'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
