# Generated by Django 5.1.5 on 2025-04-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='operator',
            field=models.CharField(choices=[('ooredoo', 'Ooredoo'), ('telecom', 'Telecom'), ('orange', 'Orange')], max_length=10, null=True),
        ),
    ]
