# Generated by Django 5.1.5 on 2025-04-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_payment_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='credit_amount',
            field=models.PositiveIntegerField(choices=[(5, '5 Credits'), (1, '1 Credits')], null=True),
        ),
    ]
